# Generated by Django 5.1.5 on 2025-04-27 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comuna',
            name='created_by',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='comuna',
            name='updated_by',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='medida',
            name='created_by',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='medida',
            name='updated_by',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='organismo',
            name='created_by',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='organismo',
            name='updated_by',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='plan',
            name='created_by',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='plan',
            name='updated_by',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='planmedida',
            name='created_by',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='planmedida',
            name='updated_by',
            field=models.EmailField(max_length=254),
        ),
    ]
