# Generated by Django 5.1.5 on 2025-04-28 03:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes_admin', '0003_comuna_created_at_comuna_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plancomuna',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plancomuna',
            name='created_by',
            field=models.EmailField(default='admin@mail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plancomuna',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='plancomuna',
            name='updated_by',
            field=models.EmailField(default='admin@mail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportemedida',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportemedida',
            name='created_by',
            field=models.EmailField(default='admin@mail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportemedida',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='reportemedida',
            name='updated_by',
            field=models.EmailField(default='admin@mail.com', max_length=254),
            preserve_default=False,
        ),
    ]
